/*
 * Respondent User Profile Basic Information API
 * Respondent User Profile Basic Information API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@eoc.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.57
 *
 * Do not edit the class manually.
 *
 */
import RespondentBasicDataApiClient from './RespondentBasicDataApiClient'
import Error from './model/Error'
import NewRespondentBasicData from './model/NewRespondentBasicData'
import RespondentBasicData from './model/RespondentBasicData'
import RespondentBasicDataApi from './api/RespondentBasicDataApi'

/**
 * Respondent_User_Profile_Basic_Information_API.<br>
 * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
 * <p>
 * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
 * <pre>
 * var RespondentUserProfileBasicInformationApi = require('index'); // See note below*.
 * var xxxSvc = new RespondentUserProfileBasicInformationApi.XxxApi(); // Allocate the API class we're going to use.
 * var yyyModel = new RespondentUserProfileBasicInformationApi.Yyy(); // Construct a model instance.
 * yyyModel.someProperty = 'someValue';
 * ...
 * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
 * ...
 * </pre>
 * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
 * and put the application logic within the callback function.</em>
 * </p>
 * <p>
 * A non-AMD browser application (discouraged) might do something like this:
 * <pre>
 * var xxxSvc = new RespondentUserProfileBasicInformationApi.XxxApi(); // Allocate the API class we're going to use.
 * var yyy = new RespondentUserProfileBasicInformationApi.Yyy(); // Construct a model instance.
 * yyyModel.someProperty = 'someValue';
 * ...
 * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
 * ...
 * </pre>
 * </p>
 * @module index
 * @version 1.0.0
 */
export {
  /**
   * The ApiClient constructor.
   * @property {module:RespondentBasicDataApiClient}
   */
  RespondentBasicDataApiClient,

  /**
   * The Error model constructor.
   * @property {module:model/Error}
   */
  Error,

  /**
   * The NewRespondentBasicData model constructor.
   * @property {module:model/NewRespondentBasicData}
   */
  NewRespondentBasicData,

  /**
   * The RespondentBasicData model constructor.
   * @property {module:model/RespondentBasicData}
   */
  RespondentBasicData,

  /**
   * The RespondentBasicDataApi service constructor.
   * @property {module:api/RespondentBasicDataApi}
   */
  RespondentBasicDataApi
}
