/*
 * Respondent User Profile Basic Information API
 * Respondent User Profile Basic Information API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@eoc.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.57
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../RespondentBasicDataApiClient'

/**
 * The NewRespondentBasicData model module.
 * @module model/NewRespondentBasicData
 * @version 1.0.0
 */
export default class NewRespondentBasicData {
  /**
   * Constructs a new <code>NewRespondentBasicData</code>.
   * @alias module:model/NewRespondentBasicData
   * @class
   * @param firstName {String}
   * @param lastName {String}
   */
  constructor(firstName, lastName) {
    this.firstName = firstName
    this.lastName = lastName
  }

  /**
   * Constructs a <code>NewRespondentBasicData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/NewRespondentBasicData} obj Optional instance to populate.
   * @return {module:model/NewRespondentBasicData} The populated <code>NewRespondentBasicData</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new NewRespondentBasicData()
      if (data.hasOwnProperty('firstName')) obj.firstName = ApiClient.convertToType(data['firstName'], 'String')
      if (data.hasOwnProperty('lastName')) obj.lastName = ApiClient.convertToType(data['lastName'], 'String')
      if (data.hasOwnProperty('email')) obj.email = ApiClient.convertToType(data['email'], 'String')
      if (data.hasOwnProperty('dateOfBirth')) obj.dateOfBirth = ApiClient.convertToType(data['dateOfBirth'], 'Date')
      if (data.hasOwnProperty('country')) obj.country = ApiClient.convertToType(data['country'], 'String')
      if (data.hasOwnProperty('city')) obj.city = ApiClient.convertToType(data['city'], 'String')
      if (data.hasOwnProperty('county')) obj.county = ApiClient.convertToType(data['county'], 'String')
      if (data.hasOwnProperty('postalCode')) obj.postalCode = ApiClient.convertToType(data['postalCode'], 'String')
      if (data.hasOwnProperty('gender')) obj.gender = ApiClient.convertToType(data['gender'], 'String')
    }
    return obj
  }
}

/**
 * @member {String} firstName
 */
NewRespondentBasicData.prototype.firstName = undefined

/**
 * @member {String} lastName
 */
NewRespondentBasicData.prototype.lastName = undefined

/**
 * @member {String} email
 */
NewRespondentBasicData.prototype.email = undefined

/**
 * @member {Date} dateOfBirth
 */
NewRespondentBasicData.prototype.dateOfBirth = undefined

/**
 * @member {String} country
 */
NewRespondentBasicData.prototype.country = undefined

/**
 * @member {String} city
 */
NewRespondentBasicData.prototype.city = undefined

/**
 * @member {String} county
 */
NewRespondentBasicData.prototype.county = undefined

/**
 * @member {String} postalCode
 */
NewRespondentBasicData.prototype.postalCode = undefined

/**
 * @member {String} gender
 */
NewRespondentBasicData.prototype.gender = undefined
