/*
 * Respondent User Profile Basic Information API
 * Respondent User Profile Basic Information API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@eoc.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.57
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../RespondentBasicDataApiClient'
import NewRespondentBasicData from './NewRespondentBasicData'

/**
 * The RespondentBasicData model module.
 * @module model/RespondentBasicData
 * @version 1.0.0
 */
export default class RespondentBasicData extends NewRespondentBasicData {
  /**
   * Constructs a new <code>RespondentBasicData</code>.
   * @alias module:model/RespondentBasicData
   * @class
   * @extends module:model/NewRespondentBasicData
   * @param id {}
   * @param firstName {}
   * @param lastName {}
   */
  constructor(id, firstName, lastName) {
    super(firstName, lastName)
    this.id = id
  }

  /**
   * Constructs a <code>RespondentBasicData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RespondentBasicData} obj Optional instance to populate.
   * @return {module:model/RespondentBasicData} The populated <code>RespondentBasicData</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RespondentBasicData()
      NewRespondentBasicData.constructFromObject(data, obj)
      if (data.hasOwnProperty('id')) obj.id = ApiClient.convertToType(data['id'], 'String')
    }
    return obj
  }
}

/**
 * @member {String} id
 */
RespondentBasicData.prototype.id = undefined
