/*
 * Respondent Profile Survey API
 * Respondent Profile Survey API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@eoc.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.57
 *
 * Do not edit the class manually.
 *
 */
import RespondentProfileSurveyApiClient from '../RespondentProfileSurveyApiClient';
import TargetGroup from './TargetGroup';

/**
 * The NewRespondentProfileSurvey model module.
 * @module model/NewRespondentProfileSurvey
 * @version 1.0.0
 */
export default class NewRespondentProfileSurvey {
  /**
   * Constructs a new <code>NewRespondentProfileSurvey</code>.
   * @alias module:model/NewRespondentProfileSurvey
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>NewRespondentProfileSurvey</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/NewRespondentProfileSurvey} obj Optional instance to populate.
   * @return {module:model/NewRespondentProfileSurvey} The populated <code>NewRespondentProfileSurvey</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new NewRespondentProfileSurvey();
      if (data.hasOwnProperty('type'))
        obj.type = RespondentProfileSurveyApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('respondentOthentSub'))
        obj.respondentOthentSub = RespondentProfileSurveyApiClient.convertToType(data['respondentOthentSub'], 'String');
      if (data.hasOwnProperty('targetGroups'))
        obj.targetGroups = RespondentProfileSurveyApiClient.convertToType(data['targetGroups'], [TargetGroup]);
    }
    return obj;
  }
}

/**
 * @member {String} type
 */
NewRespondentProfileSurvey.prototype.type = undefined;

/**
 * @member {String} respondentOthentSub
 */
NewRespondentProfileSurvey.prototype.respondentOthentSub = undefined;

/**
 * @member {Array.<module:model/TargetGroup>} targetGroups
 */
NewRespondentProfileSurvey.prototype.targetGroups = undefined;

