/*
 * Respondent Profile Survey API
 * Respondent Profile Survey API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@eoc.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.57
 *
 * Do not edit the class manually.
 *
 */
import RespondentProfileSurveyApiClient from '../RespondentProfileSurveyApiClient';

/**
 * The NewRespondentProfileSurveyIndex model module.
 * @module model/NewRespondentProfileSurveyIndex
 * @version 1.0.0
 */
export default class NewRespondentProfileSurveyIndex {
  /**
   * Constructs a new <code>NewRespondentProfileSurveyIndex</code>.
   * @alias module:model/NewRespondentProfileSurveyIndex
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>NewRespondentProfileSurveyIndex</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/NewRespondentProfileSurveyIndex} obj Optional instance to populate.
   * @return {module:model/NewRespondentProfileSurveyIndex} The populated <code>NewRespondentProfileSurveyIndex</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new NewRespondentProfileSurveyIndex();
      if (data.hasOwnProperty('currentSurveyId'))
        obj.currentSurveyId = RespondentProfileSurveyApiClient.convertToType(data['currentSurveyId'], 'String');
      if (data.hasOwnProperty('lastSurveyId'))
        obj.lastSurveyId = RespondentProfileSurveyApiClient.convertToType(data['lastSurveyId'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} currentSurveyId
 */
NewRespondentProfileSurveyIndex.prototype.currentSurveyId = undefined;

/**
 * @member {String} lastSurveyId
 */
NewRespondentProfileSurveyIndex.prototype.lastSurveyId = undefined;

