/*
 * Respondent Profile Survey API
 * Respondent Profile Survey API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@eoc.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.57
 *
 * Do not edit the class manually.
 *
 */
import RespondentProfileSurveyApiClient from '../RespondentProfileSurveyApiClient'

/**
 * The QuestionStatisticFilter model module.
 * @module model/QuestionStatisticFilter
 * @version 1.0.0
 */
export default class QuestionStatisticFilter {
  /**
   * Constructs a new <code>QuestionStatisticFilter</code>.
   * @alias module:model/QuestionStatisticFilter
   * @class
   * @param question {String}
   * @param answer {String}
   * @param country {String}
   * @param gender {String}
   */
  constructor(question, answer, country, gender) {
    this.question = question
    this.answer = answer
    this.country = country
    this.gender = gender
  }

  /**
   * Constructs a <code>QuestionStatisticFilter</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/QuestionStatisticFilter} obj Optional instance to populate.
   * @return {module:model/QuestionStatisticFilter} The populated <code>QuestionStatisticFilter</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new QuestionStatisticFilter()
      if (data.hasOwnProperty('question'))
        obj.question = RespondentProfileSurveyApiClient.convertToType(data['question'], 'String')
      if (data.hasOwnProperty('answer'))
        obj.answer = RespondentProfileSurveyApiClient.convertToType(data['answer'], 'String')
      if (data.hasOwnProperty('minAge'))
        obj.minAge = RespondentProfileSurveyApiClient.convertToType(data['minAge'], 'Number')
      if (data.hasOwnProperty('maxAge'))
        obj.maxAge = RespondentProfileSurveyApiClient.convertToType(data['maxAge'], 'Number')
      if (data.hasOwnProperty('country'))
        obj.country = RespondentProfileSurveyApiClient.convertToType(data['country'], 'String')
      if (data.hasOwnProperty('gender'))
        obj.gender = RespondentProfileSurveyApiClient.convertToType(data['gender'], 'String')
    }
    return obj
  }
}

/**
 * @member {String} question
 */
QuestionStatisticFilter.prototype.question = undefined

/**
 * @member {String} answer
 */
QuestionStatisticFilter.prototype.answer = undefined

/**
 * @member {Number} minAge
 */
QuestionStatisticFilter.prototype.minAge = undefined

/**
 * @member {Number} maxAge
 */
QuestionStatisticFilter.prototype.maxAge = undefined

/**
 * @member {String} country
 */
QuestionStatisticFilter.prototype.country = undefined

/**
 * @member {String} gender
 */
QuestionStatisticFilter.prototype.gender = undefined
