/*
 * Respondent Profile Survey API
 * Respondent Profile Survey API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@eoc.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.57
 *
 * Do not edit the class manually.
 *
 */
import RespondentProfileSurveyApiClient from '../RespondentProfileSurveyApiClient';
import NewRespondentProfileSurveyIndex from './NewRespondentProfileSurveyIndex';

/**
 * The RespondentProfileSurveyIndex model module.
 * @module model/RespondentProfileSurveyIndex
 * @version 1.0.0
 */
export default class RespondentProfileSurveyIndex extends NewRespondentProfileSurveyIndex {
  /**
   * Constructs a new <code>RespondentProfileSurveyIndex</code>.
   * @alias module:model/RespondentProfileSurveyIndex
   * @class
   * @extends module:model/NewRespondentProfileSurveyIndex
   * @param othentId {}
   */
  constructor(othentId) {
    super();
    this.othentId = othentId;
  }

  /**
   * Constructs a <code>RespondentProfileSurveyIndex</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RespondentProfileSurveyIndex} obj Optional instance to populate.
   * @return {module:model/RespondentProfileSurveyIndex} The populated <code>RespondentProfileSurveyIndex</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RespondentProfileSurveyIndex();
      NewRespondentProfileSurveyIndex.constructFromObject(data, obj);
      if (data.hasOwnProperty('othentId'))
        obj.othentId = RespondentProfileSurveyApiClient.convertToType(data['othentId'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} othentId
 */
RespondentProfileSurveyIndex.prototype.othentId = undefined;

