/*
 * Respondent Profile Survey API
 * Respondent Profile Survey API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@eoc.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.57
 *
 * Do not edit the class manually.
 *
 */
import RespondentProfileSurveyApiClient from '../RespondentProfileSurveyApiClient';
import Question from './Question';

/**
 * The TargetGroup model module.
 * @module model/TargetGroup
 * @version 1.0.0
 */
export default class TargetGroup {
  /**
   * Constructs a new <code>TargetGroup</code>.
   * @alias module:model/TargetGroup
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>TargetGroup</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TargetGroup} obj Optional instance to populate.
   * @return {module:model/TargetGroup} The populated <code>TargetGroup</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TargetGroup();
      if (data.hasOwnProperty('age'))
        obj.age = RespondentProfileSurveyApiClient.convertToType(data['age'], 'Number');
      if (data.hasOwnProperty('gender'))
        obj.gender = RespondentProfileSurveyApiClient.convertToType(data['gender'], 'String');
      if (data.hasOwnProperty('country'))
        obj.country = RespondentProfileSurveyApiClient.convertToType(data['country'], 'String');
      if (data.hasOwnProperty('surveyData'))
        obj.surveyData = RespondentProfileSurveyApiClient.convertToType(data['surveyData'], [Question]);
    }
    return obj;
  }
}

/**
 * @member {Number} age
 */
TargetGroup.prototype.age = undefined;

/**
 * @member {String} gender
 */
TargetGroup.prototype.gender = undefined;

/**
 * @member {String} country
 */
TargetGroup.prototype.country = undefined;

/**
 * @member {Array.<module:model/Question>} surveyData
 */
TargetGroup.prototype.surveyData = undefined;

