/*
 * Respondent Profile Survey API
 * Respondent Profile Survey API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@eoc.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.57
 *
 * Do not edit the class manually.
 *
 */
import RespondentProfileSurveyApiClient from './RespondentProfileSurveyApiClient';
import Error from './model/Error';
import NewRespondentProfileSurvey from './model/NewRespondentProfileSurvey';
import NewRespondentProfileSurveyIndex from './model/NewRespondentProfileSurveyIndex';
import Question from './model/Question';
import QuestionStatistic from './model/QuestionStatistic';
import QuestionStatisticFilter from './model/QuestionStatisticFilter';
import RespondentProfileSurvey from './model/RespondentProfileSurvey';
import RespondentProfileSurveyIndex from './model/RespondentProfileSurveyIndex';
import TargetGroup from './model/TargetGroup';
import QuestionStatisticApi from './api/QuestionStatisticApi';
import RespondentProfileSurveyApi from './api/RespondentProfileSurveyApi';
import RespondentProfileSurveyIndexApi from './api/RespondentProfileSurveyIndexApi';

/**
* Respondent_Profile_Survey_API.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var RespondentProfileSurveyApi = require('index'); // See note below*.
* var xxxSvc = new RespondentProfileSurveyApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new RespondentProfileSurveyApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new RespondentProfileSurveyApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new RespondentProfileSurveyApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The RespondentProfileSurveyApiClient constructor.
     * @property {module:RespondentProfileSurveyApiClient}
     */
    RespondentProfileSurveyApiClient,

    /**
     * The Error model constructor.
     * @property {module:model/Error}
     */
    Error,

    /**
     * The NewRespondentProfileSurvey model constructor.
     * @property {module:model/NewRespondentProfileSurvey}
     */
    NewRespondentProfileSurvey,

    /**
     * The NewRespondentProfileSurveyIndex model constructor.
     * @property {module:model/NewRespondentProfileSurveyIndex}
     */
    NewRespondentProfileSurveyIndex,

    /**
     * The Question model constructor.
     * @property {module:model/Question}
     */
    Question,

    /**
     * The QuestionStatistic model constructor.
     * @property {module:model/QuestionStatistic}
     */
    QuestionStatistic,

    /**
     * The QuestionStatisticFilter model constructor.
     * @property {module:model/QuestionStatisticFilter}
     */
    QuestionStatisticFilter,

    /**
     * The RespondentProfileSurvey model constructor.
     * @property {module:model/RespondentProfileSurvey}
     */
    RespondentProfileSurvey,

    /**
     * The RespondentProfileSurveyIndex model constructor.
     * @property {module:model/RespondentProfileSurveyIndex}
     */
    RespondentProfileSurveyIndex,

    /**
     * The TargetGroup model constructor.
     * @property {module:model/TargetGroup}
     */
    TargetGroup,

    /**
    * The QuestionStatisticApi service constructor.
    * @property {module:api/QuestionStatisticApi}
    */
    QuestionStatisticApi,

    /**
    * The RespondentProfileSurveyApi service constructor.
    * @property {module:api/RespondentProfileSurveyApi}
    */
    RespondentProfileSurveyApi,

    /**
    * The RespondentProfileSurveyIndexApi service constructor.
    * @property {module:api/RespondentProfileSurveyIndexApi}
    */
    RespondentProfileSurveyIndexApi
};
