/*
 * Client Survey Repository API
 * Client Survey Repository API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@eoc.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.57
 *
 * Do not edit the class manually.
 *
 */
import SurveyApiClient from './SurveyApiClient';
import Error from './model/Error';
import Survey from './model/Survey';
import SurveyRepositoryApi from './api/SurveyRepositoryApi';

/**
* Client_Survey_Repository_API.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var ClientSurveyRepositoryApi = require('index'); // See note below*.
* var xxxSvc = new ClientSurveyRepositoryApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new ClientSurveyRepositoryApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new ClientSurveyRepositoryApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new ClientSurveyRepositoryApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The SurveyApiClient constructor.
     * @property {module:SurveyApiClient}
     */
    SurveyApiClient,

    /**
     * The Error model constructor.
     * @property {module:model/Error}
     */
    Error,

    /**
     * The Survey model constructor.
     * @property {module:model/Survey}
     */
    Survey,

    /**
    * The SurveyRepositoryApi service constructor.
    * @property {module:api/SurveyRepositoryApi}
    */
    SurveyRepositoryApi
};
